
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author novicedisk
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        

    }

    private void showCard(String cardNumber) {
        CardLayout card = (CardLayout) jPanel1.getLayout();
        card.show(jPanel1, cardNumber);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel57 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton55 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton8 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel39 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jLabel40 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jLabel41 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jLabel42 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jPanel28 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jPanel33 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Heroes of Java : Beautiful life of Java");

        jPanel1.setMinimumSize(new java.awt.Dimension(539, 415));
        jPanel1.setPreferredSize(new java.awt.Dimension(540, 415));
        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel9.setPreferredSize(new java.awt.Dimension(540, 415));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setFont(new java.awt.Font("NoGameNoLife", 0, 36)); // NOI18N
        jButton7.setText("Start ");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 160, 94));

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.jpg"))); // NOI18N
        jPanel9.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel9, "card9");

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel13.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 327, 48));

        jButton14.setFont(new java.awt.Font("NoGameNoLife", 0, 18)); // NOI18N
        jButton14.setText("Entrance");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 150, 50));

        jLabel18.setFont(new java.awt.Font("NoGameNoLife", 0, 24)); // NOI18N
        jLabel18.setText("Enter your name");
        jPanel13.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.jpg"))); // NOI18N
        jPanel13.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel13, "card13");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("PLAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/order_of_tyr_by_abysswolf-d4qfesd.gif"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cha1.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ForestSunset.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel2, "card2");

        jPanel3.setPreferredSize(new java.awt.Dimension(543, 415));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("PLAY");
        jButton2.setAutoscrolls(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ChumChum_by_Ben2theEdge.gif"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cha3.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Skeletroid___Standing_by_Ben2theEdge.gif"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Skeletroid___Standing_by_Ben2theEdge.gif"))); // NOI18N
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/environment_forest_evening.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel3, "card3");

        jPanel4.setMaximumSize(new java.awt.Dimension(540, 415));
        jPanel4.setPreferredSize(new java.awt.Dimension(541, 417));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cha2.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/lightning_idle_by_abysswolf-d45r7lx.gif"))); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jButton3.setText("PLAY");
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/madara_uchiha_nzc_by_benhazard-d4e8i4e.gif"))); // NOI18N
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/madara_uchiha_nzc_by_benhazard-d4e8i4e.gif"))); // NOI18N
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/madara_uchiha_nzc_by_benhazard-d4e8i4e.gif"))); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/madara_uchiha_nzc_by_benhazard-d4e8i4e.gif"))); // NOI18N
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/marvel_vs_capcom_3_zero___idle_by_callmemra-d4gzxov.gif"))); // NOI18N
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/marvel_vs_capcom_3_zero___idle_by_callmemra-d4gzxov.gif"))); // NOI18N
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/environment_forestbackground1-1_0.png"))); // NOI18N
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel4, "card4");

        jPanel5.setPreferredSize(new java.awt.Dimension(540, 415));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton55.setText("ต่อไป");
        jButton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton55ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 70, -1));

        jButton57.setText("สิ้นสุดบทเรียน");
        jButton57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton57ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 70, -1, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/21.jpg"))); // NOI18N
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel5, "card5");

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton52.setText("ต่อไป");
        jButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton52ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 70, -1));

        jButton53.setText("กลับ");
        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton53ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 70, -1));

        jButton54.setText("หน้าแรก");
        jButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton54ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 70, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/22.jpg"))); // NOI18N
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel6, "card6");

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton49.setText("ต่อไป");
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 70, -1));

        jButton50.setText("กลับ");
        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 70, -1));

        jButton51.setText("หน้าแรก");
        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 70, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/23.jpg"))); // NOI18N
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel7, "card7");

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton46.setText("ต่อไป");
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 70, -1));

        jButton47.setText("กลับ");
        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 70, -1));

        jButton48.setText("หน้าแรก");
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 70, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/24.jpg"))); // NOI18N
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel8, "card8");

        jPanel10.setPreferredSize(new java.awt.Dimension(544, 415));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton43.setText("ต่อไป");
        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 70, -1));

        jButton44.setText("กลับ");
        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 70, -1));

        jButton45.setText("หน้าแรก");
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 70, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/25.jpg"))); // NOI18N
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel10, "card10");

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton40.setText("ต่อไป");
        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 70, -1));

        jButton41.setText("กลับ");
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 70, -1));

        jButton42.setText("หน้าแรก");
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });
        jPanel11.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 70, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/26.jpg"))); // NOI18N
        jPanel11.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel11, "card11");

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton37.setText("ต่อไป");
        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 70, -1));

        jButton38.setText("กลับ");
        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 70, -1));

        jButton39.setText("หน้าแรก");
        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });
        jPanel12.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 70, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/27.jpg"))); // NOI18N
        jPanel12.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel12, "card12");

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton34.setText("ต่อไป");
        jButton34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton34ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 70, -1));

        jButton35.setText("กลับ");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 70, -1));

        jButton36.setText("หน้าแรก");
        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 70, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/28.jpg"))); // NOI18N
        jPanel14.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel14, "card14");

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton31.setText("ต่อไป");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 70, -1));

        jButton32.setText("กลับ");
        jButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton32ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 70, -1));

        jButton33.setText("หน้าแรก");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 70, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/29.jpg"))); // NOI18N
        jPanel15.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel15, "card15");

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton28.setText("ต่อไป");
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 70, -1));

        jButton29.setText("กลับ");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 70, -1));

        jButton30.setText("หน้าแรก");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel16.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 70, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/30.jpg"))); // NOI18N
        jPanel16.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel16, "card16");

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton25.setText("ต่อไป");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 70, -1));

        jButton26.setText("กลับ");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 70, -1));

        jButton27.setText("หน้าแรก");
        jButton27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton27ActionPerformed(evt);
            }
        });
        jPanel17.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 70, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/31.jpg"))); // NOI18N
        jPanel17.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel17, "card17");

        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton19.setText("กลับ");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 70, -1));

        jButton20.setText("หน้าแรก");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 70, -1));

        jButton21.setText("ต่อไป");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel18.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 70, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/32.jpg"))); // NOI18N
        jPanel18.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel18, "card18");

        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton22.setText("ต่อไป");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 70, -1));

        jButton23.setText("กลับ");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 70, -1));

        jButton24.setText("หน้าแรก");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 70, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/33.jpg"))); // NOI18N
        jPanel19.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel19, "card19");

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton15.setText("หน้าแรก");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        jButton16.setText("กลับ");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 70, -1));

        jButton4.setText("สิ้นสุดบทเรียน");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/34.jpg"))); // NOI18N
        jPanel20.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel20, "card20");

        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setText("เริ่ม");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        jButton6.setText("ออก");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel21.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Dark_Forest0.jpg"))); // NOI18N
        jPanel21.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel21, "card21");

        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/linux.jpg"))); // NOI18N
        jPanel26.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 40));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/100px-Java_logo_and_wordmark.svg.png"))); // NOI18N
        jPanel26.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 40, 40));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Red-Hat.jpg"))); // NOI18N
        jPanel26.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, 40));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/apple.jpg"))); // NOI18N
        jPanel26.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        jRadioButton1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(jRadioButton1);
        jPanel26.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jRadioButton2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(jRadioButton2);
        jPanel26.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jRadioButton3.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(jRadioButton3);
        jPanel26.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jRadioButton4.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup2.add(jRadioButton4);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jPanel26.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        jButton8.setText("ข้อต่อไป");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel26.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Dark_Forest1.jpg"))); // NOI18N
        jPanel26.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel26, "card22");

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setText("ข้อต่อไป");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel22.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        jRadioButton5.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton5.setText("JVM");
        jPanel22.add(jRadioButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jRadioButton6.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton6.setText("JRE");
        jPanel22.add(jRadioButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jRadioButton7.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton7.setText("JKF");
        jPanel22.add(jRadioButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jRadioButton8.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton8.setText("JDK");
        jPanel22.add(jRadioButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Dark_Forest2.jpg"))); // NOI18N
        jPanel22.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel22, "card23");

        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setText("ข้อต่อไป");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel23.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        jRadioButton9.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup3.add(jRadioButton9);
        jRadioButton9.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton9.setText("James Gosling");
        jPanel23.add(jRadioButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jRadioButton10.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup3.add(jRadioButton10);
        jRadioButton10.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton10.setText("James Cameron");
        jPanel23.add(jRadioButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jRadioButton11.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup3.add(jRadioButton11);
        jRadioButton11.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton11.setText("Mark Zuckerberg");
        jPanel23.add(jRadioButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jRadioButton12.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup3.add(jRadioButton12);
        jRadioButton12.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton12.setText("Bill Gates");
        jPanel23.add(jRadioButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Dark_Forest3.jpg"))); // NOI18N
        jPanel23.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel23, "card24");

        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setText("ข้อต่อไป");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel25.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        jRadioButton13.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup4.add(jRadioButton13);
        jRadioButton13.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton13.setText("JAVA WORLD");
        jPanel25.add(jRadioButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jRadioButton14.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup4.add(jRadioButton14);
        jRadioButton14.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton14.setText("JAVA");
        jPanel25.add(jRadioButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jRadioButton15.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup4.add(jRadioButton15);
        jRadioButton15.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton15.setText("WORLD");
        jPanel25.add(jRadioButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jRadioButton16.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup4.add(jRadioButton16);
        jRadioButton16.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton16.setText("\"JAVA WORLD\"");
        jPanel25.add(jRadioButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Dark_Forest4.jpg"))); // NOI18N
        jPanel25.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel25, "card25");

        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton12.setText("ส่งคำตอบ");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel24.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        jRadioButton17.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup5.add(jRadioButton17);
        jRadioButton17.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton17.setText("String x = \"ARM HEADSHOT\";");
        jPanel24.add(jRadioButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jRadioButton18.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup5.add(jRadioButton18);
        jRadioButton18.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton18.setText("String x = 123;");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });
        jPanel24.add(jRadioButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jRadioButton19.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup5.add(jRadioButton19);
        jRadioButton19.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton19.setText("int x = 123;");
        jPanel24.add(jRadioButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jRadioButton20.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup5.add(jRadioButton20);
        jRadioButton20.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton20.setText("double x = 123.123;");
        jPanel24.add(jRadioButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Dark_Forest5.jpg"))); // NOI18N
        jPanel24.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel24, "card26");

        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cha3.png"))); // NOI18N
        jPanel27.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/environment_forest_evening.png"))); // NOI18N
        jPanel27.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton13.setText("jButton13");
        jButton13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton13KeyPressed(evt);
            }
        });
        jPanel27.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jPanel1.add(jPanel27, "card27");

        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel44.setText("jLabel44");
        jPanel28.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(-32768, -32768, -1, -1));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/end1.jpg"))); // NOI18N
        jPanel28.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel28, "card28");

        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setText("jLabel45");
        jPanel29.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(-32768, -32768, -1, -1));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/end2.jpg"))); // NOI18N
        jPanel29.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel29, "card29");

        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setText("jLabel46");
        jPanel30.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(-32768, -32768, -1, -1));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/end3.jpg"))); // NOI18N
        jPanel30.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel30, "card30");

        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setText("jLabel47");
        jPanel31.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(-32768, -32768, -1, -1));

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/end4.jpg"))); // NOI18N
        jPanel31.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel31, "card31");

        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setText("jLabel48");
        jPanel32.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(-32768, -32768, -1, -1));

        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cha1.png"))); // NOI18N
        jPanel32.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bedroo,.png"))); // NOI18N
        jPanel32.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(jPanel32, "card32");

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/gameOver.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel33Layout = new javax.swing.GroupLayout(jPanel33);
        jPanel33.setLayout(jPanel33Layout);
        jPanel33Layout.setHorizontalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addComponent(jLabel56)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel33Layout.setVerticalGroup(
            jPanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel33Layout.createSequentialGroup()
                .addComponent(jLabel56)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel33, "card33");

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/endcre.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addComponent(jLabel59)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addComponent(jLabel59)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel34, "card34");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed

        if (evt.getKeyCode() == evt.VK_W) {
            jLabel4.setBounds(jLabel4.getBounds().x, jLabel4.getBounds().y - 7, 30, 50);
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cha4.png"))); // NOI18N

        }
        if (evt.getKeyCode() == evt.VK_S) {
            jLabel4.setBounds(jLabel4.getBounds().x, jLabel4.getBounds().y + 7, 30, 50);
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cha1.png"))); // NOI18N

        }
        if (evt.getKeyCode() == evt.VK_A) {
            jLabel4.setBounds(jLabel4.getBounds().x - 7, jLabel4.getBounds().y, 30, 50);
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cha2.png"))); // NOI18N

        }
        if (evt.getKeyCode() == evt.VK_D) {
            jLabel4.setBounds(jLabel4.getBounds().x + 7, jLabel4.getBounds().y, 30, 50);
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cha3.png"))); // NOI18N

        }

        if ((jLabel4.getBounds().y <= 100)) {
            jLabel4.setBounds(jLabel4.getBounds().x, jLabel4.getBounds().y + 7, 30, 50);
            JOptionPane.showMessageDialog(null,
                    "ยินดีต้อนรับเจ้าหนู ที่นี่คือ JAVAWORLD ทุกสิ่งทุกอย่างที่นี่ถูกสร้างขึ้นจากภาษาJAVA",
                    "สามผู้กล้า",
                    JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null,
                    "ถ้าหากเจ้าไม่สามารถตอบคำถามของจอมมารได้ เจ้าจะติดอยู่ที่นี่ไปตลอดกาล",
                    "สามผู้กล้า",
                    JOptionPane.INFORMATION_MESSAGE);
            JOptionPane.showMessageDialog(null,
                    "ก่อนที่เจ้าจะตอบคำถามกับจอมมารนั้น เจ้าจงไปศึกษาหาความรู้เรื่องเกี่ยวกับJAVA จากหัวหน้าผู้กล้าที่อยู่ในป่าฝั่งซ้ายก่อน",
                    "สามผู้กล้า",
                    JOptionPane.INFORMATION_MESSAGE);

        } else if ((jLabel4.getBounds().y >= 360)) {
            jLabel4.setBounds(jLabel4.getBounds().x, jLabel4.getBounds().y - 7, 30, 50);
        } else if ((jLabel4.getBounds().x <= 0)) {
            showCard("card4");
        } else if ((jLabel4.getBounds().x >= 544)) {

            showCard("card3");
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        if (evt.getKeyCode() == evt.VK_W) {
            jLabel5.setBounds(jLabel5.getBounds().x, jLabel5.getBounds().y - 7, 30, 50);
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cha4.png"))); // NOI18N

        }
        if (evt.getKeyCode() == evt.VK_S) {
            jLabel5.setBounds(jLabel5.getBounds().x, jLabel5.getBounds().y + 7, 30, 50);
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cha1.png"))); // NOI18N

        }
        if (evt.getKeyCode() == evt.VK_A) {
            jLabel5.setBounds(jLabel5.getBounds().x - 7, jLabel5.getBounds().y, 30, 50);
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cha2.png"))); // NOI18N

        }
        if (evt.getKeyCode() == evt.VK_D) {
            jLabel5.setBounds(jLabel5.getBounds().x + 7, jLabel5.getBounds().y, 30, 50);
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cha3.png"))); // NOI18N

        }

        if ((jLabel5.getBounds().y <= 200)) {
            jLabel5.setBounds(jLabel5.getBounds().x, jLabel5.getBounds().y + 7, 30, 50);

        } else if ((jLabel5.getBounds().y >= 360)) {
            jLabel5.setBounds(jLabel5.getBounds().x, jLabel5.getBounds().y - 7, 30, 50);
        } else if ((jLabel5.getBounds().x <= 0)) {
            showCard("card2");

        } else if ((jLabel5.getBounds().x >= 340)) {
            jLabel5.setBounds(jLabel5.getBounds().x - 7, jLabel5.getBounds().y, 30, 50);
            JOptionPane.showMessageDialog(null,
                    "ห้ามผ่าน ถ้าหากเจ้ายังตอบคำถามของข้าไม่ได้",
                    "จอมมาร",
                    JOptionPane.WARNING_MESSAGE);
            JOptionPane.showMessageDialog(null,
                    "ถ้ายังดื้อด้านที่จะผ่านไปล่ะก็ เจ้าต้องตายเหมือนเจ้าพวกนี้แหละ",
                    "จอมมาร",
                    JOptionPane.WARNING_MESSAGE);
            Object[] options = {"ใช่..ข้าพร้อมแล้ว", "ไม่..ข้ายังไม่พร้อม"};
            int n = JOptionPane.showOptionDialog(null,
                    "ว่าไงเจ้าหนู เจ้าพร้อมที่จะตอบคำถามของข้าแล้วหรือไม่?",
                    "จอมมาร",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null, //do not use a custom Icon
                    options, //the titles of buttons
                    options[0]); //default button title
            if (n == 0) {
                showCard("card21");
            }

        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed

        if (evt.getKeyCode() == evt.VK_W) {
            jLabel6.setBounds(jLabel6.getBounds().x, jLabel6.getBounds().y - 7, 30, 50);
            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cha4.png"))); // NOI18N

        }
        if (evt.getKeyCode() == evt.VK_S) {
            jLabel6.setBounds(jLabel6.getBounds().x, jLabel6.getBounds().y + 7, 30, 50);
            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cha1.png"))); // NOI18N

        }
        if (evt.getKeyCode() == evt.VK_A) {
            jLabel6.setBounds(jLabel6.getBounds().x - 7, jLabel6.getBounds().y, 30, 50);
            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cha2.png"))); // NOI18N

        }
        if (evt.getKeyCode() == evt.VK_D) {
            jLabel6.setBounds(jLabel6.getBounds().x + 7, jLabel6.getBounds().y, 30, 50);
            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cha3.png"))); // NOI18N

        }

        if ((jLabel6.getBounds().y <= 200)) {
            jLabel6.setBounds(jLabel6.getBounds().x, jLabel6.getBounds().y + 7, 30, 50);
        } else if ((jLabel6.getBounds().y >= 360)) {
            jLabel6.setBounds(jLabel6.getBounds().x, jLabel6.getBounds().y - 7, 30, 50);

        } else if ((jLabel6.getBounds().x <= 100)) {
            jLabel6.setBounds(jLabel6.getBounds().x + 7, jLabel6.getBounds().y, 30, 50);
            JOptionPane.showMessageDialog(null,
                    "ในการที่จะเอาชนะจอมมารได้นั้น จำเป็นต้องใช้ความรู้มากมาย",
                    "หัวหน้าผู้กล้า",
                    JOptionPane.INFORMATION_MESSAGE);

            Object[] options = {"ใช่..ข้าพร้อมแล้ว", "ไม่..ข้ายังไม่พร้อม"};
            int n = JOptionPane.showOptionDialog(null,
                    "ว่าไงท่าน " + name + " ท่านพร้อมที่จะศึกษาบทเรียนเกี่ยวกับJAVAแล้วหรือยัง",
                    "หัวหน้าผู้กล้า",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null, //do not use a custom Icon
                    options, //the titles of buttons
                    options[0]); //default button title
            if (n == 0) {
                showCard("card5");
            }

        } else if ((jLabel6.getBounds().x >= 540)) {
            showCard("card2"); //jLabel6.setBounds(jLabel6.getBounds().x - 7, jLabel6.getBounds().y, 30, 50);

        }

    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        showCard("card13");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        if (jTextField1.getText().equals("")) {
            JOptionPane.showMessageDialog(null,
                    "ท่านผู้กล้า กรุณากรอกชื่อของท่านด้วย",
                    "SYSTEM",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            name = jTextField1.getText();
            showCard("card2");
            JOptionPane.showMessageDialog(null,
                    "เอ๊ะที่นี่คือที่ไหนกัน??",
                    name,
                    JOptionPane.QUESTION_MESSAGE);
            JOptionPane.showMessageDialog(null,
                    "เราจำได้ว่า เมื่อตะกี้เรายังอยู่ที่ห้องนอนไม่ใช่หรอ??",
                    name,
                    JOptionPane.QUESTION_MESSAGE);
            JOptionPane.showMessageDialog(null,
                    "งั้นลองสำรวจที่นี่ ดูก่อนแล้วกัน...",
                    name,
                    JOptionPane.QUESTION_MESSAGE);

        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton55ActionPerformed
        showCard("card6");
    }//GEN-LAST:event_jButton55ActionPerformed

    private void jButton57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton57ActionPerformed
        showCard("card4");
    }//GEN-LAST:event_jButton57ActionPerformed

    private void jButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton52ActionPerformed
        showCard("card7");
    }//GEN-LAST:event_jButton52ActionPerformed

    private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton53ActionPerformed
        showCard("card5");
    }//GEN-LAST:event_jButton53ActionPerformed

    private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton54ActionPerformed
        showCard("card5");
    }//GEN-LAST:event_jButton54ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        showCard("card8");
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        showCard("card6");
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
       showCard("card5");
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
       showCard("card10");
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        showCard("card7");
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        showCard("card5");
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        showCard("card11");
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
       showCard("card8");
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        showCard("card5");
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        showCard("card12");
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        showCard("card10");
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        showCard("card5");
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
       showCard("card14");
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        showCard("card11");
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        showCard("card5");
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton34ActionPerformed
        showCard("card15");
    }//GEN-LAST:event_jButton34ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
       showCard("card12");
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
       showCard("card5");
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        showCard("card16");
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton32ActionPerformed
        showCard("card14");
    }//GEN-LAST:event_jButton32ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
       showCard("card5");
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        showCard("card17");
    }//GEN-LAST:event_jButton28ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        showCard("card15");
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
       showCard("card5");
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        showCard("card18");
    }//GEN-LAST:event_jButton25ActionPerformed

    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
       showCard("card16");
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jButton27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton27ActionPerformed
       showCard("card5");
    }//GEN-LAST:event_jButton27ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        showCard("card19");
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        showCard("card17");
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        showCard("card5");
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        showCard("card20");
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        showCard("card18");
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        showCard("card5");
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        showCard("card19");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        showCard("card5");
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        showCard("card4");
        JOptionPane.showMessageDialog(null,
                    "ในเมื่อท่านพร้อมแล้ว ก็ไปตอบคำถามของจอมมารได้เลย!",
                    "หัวหน้าผู้กล้า",
                    JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(null,
                    "จอมมารจะอาศัยอยู่ในป่ามืด ฝั่งขวาให้ท่านเดินไปเรื่อยๆ จะพบกับจอมมารเอง",
                    "หัวหน้าผู้กล้า",
                    JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(null,
                    "ข้าคงแนะนำท่านได้เพียงเท่านี้ ขอให้ท่านโชคดี",
                    "หัวหน้าผู้กล้า",
                    JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        showCard("card3");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       showCard("card22");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
      showCard("card23");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        showCard("card24");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       showCard("card25");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        showCard("card26");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        
        if(       jRadioButton2.isSelected()==true
                &&jRadioButton7.isSelected()==true
                &&jRadioButton9.isSelected()==true
                &&jRadioButton13.isSelected()==true
                &&jRadioButton18.isSelected()==true){
        showCard("card27");
        JOptionPane.showMessageDialog(null,
                    "เก่งมากที่ตอบคำถามจอมมารอย่างข้าได้ ข้าให้เจ้าผ่านไปได้",
                    "จอมมาร",
                    JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(null,
                    "เอาหล่ะ ให้เจ้าเดินต่อไปเรื่อยๆ จะเห็นแสงสว่างที่ปลายทางของป่า",
                    "จอมมาร",
                    JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(null,
                    "และอย่าลืม วิชาความรู้ที่เจ้าได้เรียนไปด้วยหละ มันจะมีประโยชน์ต่อเจ้าใจอนาคต...",
                    "จอมมาร",
                    JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(null,
                    "จอมมาร.. หายไปแล้วว..",
                    name,
                    JOptionPane.PLAIN_MESSAGE);
        JOptionPane.showMessageDialog(null,
                    "เอาหละ ได้เวลากลับแล้ว..",
                    name,
                    JOptionPane.PLAIN_MESSAGE);
        }
        else{
        showCard("card3");
        JOptionPane.showMessageDialog(null,
                    "ฮ่าๆๆ เจ้าไม่ผ่าน",
                    "จอมมาร",
                    JOptionPane.WARNING_MESSAGE);
        JOptionPane.showMessageDialog(null,
                    "ถ้าเจ้ายังไม่สามารถตอบคำข้าได้ ก็จงติดอยู่ในนี้ไปตลอดกาลเถอะ",
                    "จอมมาร",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton13KeyPressed
      if (evt.getKeyCode() == evt.VK_W) {
            jLabel49.setBounds(jLabel49.getBounds().x, jLabel49.getBounds().y - 7, 30, 50);
            jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cha4.png"))); // NOI18N

        }
        if (evt.getKeyCode() == evt.VK_S) {
            jLabel49.setBounds(jLabel49.getBounds().x, jLabel49.getBounds().y + 7, 30, 50);
            jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cha1.png"))); // NOI18N

        }
        if (evt.getKeyCode() == evt.VK_A) {
            jLabel49.setBounds(jLabel49.getBounds().x - 7, jLabel49.getBounds().y, 30, 50);
            jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cha2.png"))); // NOI18N

        }
        if (evt.getKeyCode() == evt.VK_D) {
            jLabel49.setBounds(jLabel49.getBounds().x + 7, jLabel49.getBounds().y, 30, 50);
            jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cha3.png"))); // NOI18N

        }

        if ((jLabel49.getBounds().y <= 200)) {
            jLabel49.setBounds(jLabel49.getBounds().x, jLabel49.getBounds().y + 7, 30, 50);

        } else if ((jLabel49.getBounds().y >= 360)) {
            jLabel49.setBounds(jLabel49.getBounds().x, jLabel49.getBounds().y - 7, 30, 50);
        } else if ((jLabel49.getBounds().x <= 0)) {
            jLabel49.setBounds(jLabel49.getBounds().x+7, jLabel49.getBounds().y, 30, 50);

        } else if ((jLabel49.getBounds().x >= 540)) {
          
            showCard("card28");
            JOptionPane.showMessageDialog(null,
                    "ในที่สุดเราก็ได้ออกจากที่นี่..",
                    name,
                    JOptionPane.PLAIN_MESSAGE);
            JOptionPane.showMessageDialog(null,
                    "การเดินทางของเราสิ้นสุดเพียงเท่านี้สินะ...",
                    name,
                    JOptionPane.QUESTION_MESSAGE);
            JOptionPane.showMessageDialog(null,
                    "แสงสว่างนั้นคงเป็นทางออกแน่ๆ",
                    name,
                    JOptionPane.PLAIN_MESSAGE);
            showCard("card29");
            JOptionPane.showMessageDialog(null,
                    "อ่า..รู้สึกง่วงจัง",
                    name,
                    JOptionPane.PLAIN_MESSAGE);
            JOptionPane.showMessageDialog(null,
                    "เดินต่อไปไม่ไหวแล้ว..",
                    name,
                    JOptionPane.PLAIN_MESSAGE);
                    showCard("card30");
            JOptionPane.showMessageDialog(null,
                    "ขอพักตรงนี้ก่อนแล้วกัน",
                    name,
                    JOptionPane.PLAIN_MESSAGE);
                    showCard("card31");
                    JOptionPane.showMessageDialog(null,
                    "กริ๊งงงงงงงงงงงง !!!!!!! ",
                    "นาฬิกาปลุก",
                    JOptionPane.WARNING_MESSAGE);
                    
                    JOptionPane.showMessageDialog(null,
                    "เอ๊ะ ????",
                    name,
                    JOptionPane.QUESTION_MESSAGE);
                    showCard("card32");
                    JOptionPane.showMessageDialog(null,
                    "นี่เราฝันไปหรอเนี่ย...",
                    name,
                    JOptionPane.QUESTION_MESSAGE);
                    JOptionPane.showMessageDialog(null,
                    "ถึงแม้จะเป็นเพียงแค่ความฝัน แต่มันก็สนุกมากเลย",
                    name,
                    JOptionPane.QUESTION_MESSAGE);
                    showCard("card33");
                    JOptionPane.showMessageDialog(null,
                    "THANKS FOR PLAYING",
                    "STAFF",
                    JOptionPane.INFORMATION_MESSAGE);
                    showCard("card34");
                    
                    
                    
        }
        
        
            
    }//GEN-LAST:event_jButton13KeyPressed

    private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton18ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    String name;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
